export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  LOCATION_CONFLICT: "LOCATION_CONFLICT",
  TASK_NOT_PENDING: "TASK_NOT_PENDING",
  ENTITY_NOT_FOUND: "ENTITY_NOT_FOUND"
} as const;
