export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  LOCATION_CONFLICT: "LOCATION_CONFLICT",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
  CONFLICT_ALREADY_RESOLVED: "CONFLICT_ALREADY_RESOLVED",
  LOCATION_REQUIRED: "LOCATION_REQUIRED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
